# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     target/*.war
     
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'veracode'
    veracodeAppProfile: 'Verademo'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    maximumWaitTime: '360'
    apiId: 

parameters:
  - name: veracode_sca_token
    type: string
steps:
  - task: Bash@3
    displayName: 'Veracode SCA scan'
    inputs:
      targetType: 'inline'
      script: |
            export SRCCLR_API_TOKEN="${{parameters.veracode_sca_token}}"
            curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --update-advisor

  - task: Veracode@3
    displayName: 'Veracode Upload and Scan'
    inputs:
      ConnectionDetailsSelection: 'Endpoint'
      AnalysisService: 'veracode'
      veracodeAppProfile: 'Verademo'
      version: '$(build.buildNumber)'
      filepath: '$(build.artifactstagingdirectory)'
      sandboxName: 'ADO'
      createSandBox: true
      createProfile: true
      maximumWaitTime: '360'